Diplom/WebApplicationMVC/Controllers/AdminController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVC.Models.Database;

namespace WebApplicationMVC.Controllers;

[Authorize("admin")]
public class AdminController : Controller
{
    private readonly AppDbContext _context;

    public AdminController(AppDbContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        var avatarDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "avatars");
        var allAvatars = Directory.GetFiles(avatarDir).Select(Path.GetFileName).ToList();
        var rng = new Random();
        ViewBag.Avatar = allAvatars.Any()
            ? "/images/avatars/" + allAvatars[rng.Next(allAvatars.Count)]
            : "/images/icon.png";

        //для отображения в ЛК
        if (int.TryParse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value, out int userId))
        {
            var user = _context.Users.FirstOrDefault(u => u.Id == userId);
            if (user != null)
            {
                ViewBag.Phone = user.Number;
                ViewBag.Email = user.Login;
                ViewBag.FullName = $"{user.LastName} {user.FirstName} {user.MiddleName}";
            }
        }

        return View();
    }
}

Diplom/WebApplicationMVC/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVC.Models.Database;
using WebApplicationMVC.ViewModels.Students;

namespace WebApplicationMVC.Controllers;

public class StudentsController : Controller
{
    private readonly AppDbContext _context;

    public StudentsController(AppDbContext context)
    {
        _context = context;
    }

    // GET: Students
    public async Task<IActionResult> Index()
    {
        var students = await _context
            .Students.Select(s => new StudentViewModel()
            {
                Id = s.Id,
                StudentName = $"{s.LastName} {s.FirstName}{(string.IsNullOrEmpty(s.MiddleName) ? "" : " " + s.MiddleName)}"
            })
            .ToListAsync();

        return View(students);
    }

    // GET: Students/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();

        var student = await _context.Students
            .Include(s => s.Group)
            .Include(s => s.User)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (student == null)
            return NotFound();

        var studentView = new StudentDetailsViewModel()
        {
            Id = student.Id,
            FirstName = student.FirstName,
            LastName = student.LastName,
            MiddleName = student.MiddleName,
            DateOfBirth = student.DateOfBirth,
            GroupId = student.GroupId,
            GroupName = student.Group.Name,
            ParentName = student.User.FirstName +
            " " + student.User.LastName + " " + student.MiddleName
        };

        return View(studentView);
    }

    // GET: Students/Create
    public async Task<IActionResult> Create()
    {
        await SetParentsForViewBagAsync();
        await SetGroupsForViewBagAsync();
        await SetTeachersForViewBagAsync();
        await SetCoursesForViewBagAsync();
        return View();
    }

    // POST: Students/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateStudentFormModel model)
    {
        if (ModelState.IsValid)
        {
            var parent = await _context
                .Users
                .Where(x => x.AppRole == AppRole.Parent)
                .FirstOrDefaultAsync(x => x.Id == model.ParentId);

            if (parent == null)
            {
                ModelState.AddModelError("ParentId", "Ошибка при выборе родителя");
                await SetParentsForViewBagAsync(model.ParentId);
                await SetGroupsForViewBagAsync(model.GroupId);
                await SetTeachersForViewBagAsync(model.TeacherId);
                await SetCoursesForViewBagAsync(model.CourseId);

                return View(model);
            }

            var isDuplicate = await _context.Students.AnyAsync(s =>
                s.FirstName.ToLower() == model.FirstName.ToLower() &&
                s.LastName.ToLower() == model.LastName.ToLower() &&
                s.MiddleName.ToLower() == model.MiddleName.ToLower() &&
                s.DateOfBirth == model.DateOfBirth &&
                s.UserId == model.ParentId
                );

            if (isDuplicate)
            {
                ModelState.AddModelError(string.Empty, "Такой ученик уже существует.");
                await SetParentsForViewBagAsync(model.ParentId);
                await SetGroupsForViewBagAsync(model.GroupId);
                await SetTeachersForViewBagAsync(model.TeacherId);
                await SetCoursesForViewBagAsync(model.CourseId);
                return View(model);
            }

            Group group;

            if (model.IsPrivate)
            {
                var course = await _context
                    .Courses.FirstOrDefaultAsync(c => c.Id == model.CourseId);

                if (course == null)
                {
                    ModelState.AddModelError("CourseId", "Ошибка при выборе курса");
                    await SetParentsForViewBagAsync(model.ParentId);
                    await SetGroupsForViewBagAsync(model.GroupId);
                    await SetTeachersForViewBagAsync(model.TeacherId);
                    await SetCoursesForViewBagAsync(model.CourseId);
                    return View(model);
                }

                var teacher = await _context
                    .Users
                    .FirstOrDefaultAsync(x => x.Id == model.TeacherId && x.AppRole == AppRole.Teacher);

                if (teacher == null || teacher.AppRole != AppRole.Teacher)
                {
                    ModelState.AddModelError("TeacherId", "Ошибка при выборе преподователя");
                    await SetParentsForViewBagAsync(model.ParentId);
                    await SetGroupsForViewBagAsync(model.GroupId);
                    await SetTeachersForViewBagAsync(model.TeacherId);
                    await SetCoursesForViewBagAsync(model.CourseId);
                    return View(model);
                }

                group = new Group()
                {
                    GroupType = GroupType.Personal,
                    //CourseId = course.Id,
                    Course = course,
                    Teacher = teacher,
                    Name = "---"
                };
            }
            else
            {
                var groupFromDb = await _context
                    .Groups
                    .FirstOrDefaultAsync(x => x.Id == model.GroupId);

                if (groupFromDb == null)
                {
                    ModelState.AddModelError("GroupId", "Ошибка при выборе группы");
                    await SetParentsForViewBagAsync(model.ParentId);
                    await SetGroupsForViewBagAsync(model.GroupId);
                    await SetTeachersForViewBagAsync(model.TeacherId);
                    await SetCoursesForViewBagAsync(model.CourseId);
                    return View(model);
                }

                group = groupFromDb;
            }

            var student = new Student()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                MiddleName = model.MiddleName,
                DateOfBirth = model.DateOfBirth,
                Group = group,
                User = parent,
                Balance = model.Balance
            };

            _context.Add(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        await SetParentsForViewBagAsync();
        await SetGroupsForViewBagAsync();
        return View(nameof(Create));
    }

    // GET: Students/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
            return NotFound();

        var student = await _context
            .Students
            .Include(s => s.Group)
            .FirstOrDefaultAsync(s => s.Id == id);

        if (student == null)
            return NotFound();

        await SetGroupsForViewBagAsync(student.GroupId);
        await SetParentsForViewBagAsync(student.UserId);

        var studentEditViewModel = new EditStudentFormModel()
        {
            Id = student.Id,
            FirstName = student.FirstName,
            LastName = student.LastName,
            MiddleName = student.MiddleName,
            DateOfBirth = student.DateOfBirth,
            GroupId = student.GroupId,
            ParentId = (int)(student.UserId),
            IsPrivate = student.Group.GroupType == GroupType.Personal,
            Balance = student.Balance
        };

        return View(studentEditViewModel);
    }

    // POST: Students/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, EditStudentFormModel model)
    {
        if (id != model.Id)
            return NotFound();

        if (ModelState.IsValid)
        {

            try
            {
                var student = await _context
                    .Students
                    .FirstOrDefaultAsync(x => x.Id == model.Id);
                if (student == null)
                    return NotFound();

                var group = await _context
                .Groups
                .FirstOrDefaultAsync(x => x.Id == model.GroupId);

                if (group == null)
                {
                    ModelState.AddModelError("GroupId", "Ошибка при выборе группы");
                    await SetParentsForViewBagAsync(model.ParentId);
                    await SetGroupsForViewBagAsync(model.GroupId);
                    return View(model);
                }

                var parent = await _context
                    .Users
                    .Where(x => x.AppRole == AppRole.Parent)
                    .FirstOrDefaultAsync(x => x.Id == model.ParentId);

                if (parent == null)
                {
                    ModelState.AddModelError("ParentId", "Ошибка при выборе родителя");
                    await SetParentsForViewBagAsync(model.ParentId);
                    await SetGroupsForViewBagAsync(model.GroupId);
                    return View(model);
                }

                student.FirstName = model.FirstName;
                student.LastName = model.LastName;
                student.MiddleName = model.MiddleName;
                student.DateOfBirth = model.DateOfBirth;
                student.User = parent;
                student.Balance = model.Balance;

                if (!model.IsPrivate)
                    student.Group = group;

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await IsStudentExistAsync(model.Id))
                    return NotFound();
            }

Diplom/WebApplicationMVC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVC.Models.Database;
using WebApplicationMVC.ViewModels.Users;

namespace WebApplicationMVC.Controllers;

[Authorize("admin")]
public class UsersController : Controller
{
    private readonly AppDbContext _context;

    public UsersController(AppDbContext context)
    {
        _context = context;
    }

    // GET: Users
    public async Task<IActionResult> Index()
    {
        var users = await _context
            .Users
            .Select(u => new UserViewModel()
            {
                Id = u.Id,
                UserName = u.FirstName + " " + u.LastName + " " + u.MiddleName,
                AppRole = u.GetRole()
            })
            .ToListAsync();
        return View(users);
    }

    // GET: Users/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();

        var user = await _context.Users
            .Select(u => new UserDetailsViewModel()
            {
                Id = u.Id,
                FirstName = u.FirstName,
                LastName = u.LastName,
                MiddleName = u.MiddleName,
                Login = u.Login,
                Number = u.Number,
                DateOfBirth = u.DateOfBirth,
                AppRole = u.GetRole()
            })
            .FirstOrDefaultAsync(m => m.Id == id);
        if (user == null)
            return NotFound();

        return View(user);
    }

    // GET: Users/Create
    public IActionResult Create()
    {
        SetAppRoles();
        return View();
    }

    // POST: Users/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateUserFormModel model)
    {
        if (await _context.Users.AnyAsync(u => u.Login == model.Login))
        {
            ModelState.AddModelError("Login", "This login is already taken.");
            SetAppRoles(model.AppRole);
            return View(model);
        }

        if (ModelState.IsValid)
        {
            var user = new User()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                MiddleName = model.MiddleName,
                Login = model.Login,
                Number = model.Number,
                Password = model.Password,
                DateOfBirth = DateOnly.FromDateTime(model.DateOfBirth),
                AppRole = (AppRole)model.AppRole
            };
            _context.Add(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        SetAppRoles(model.AppRole);
        return View(model);
    }

    // GET: Users/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
            return NotFound();

        var user = await _context.Users.FindAsync(id);
        if (user == null)
            return NotFound();

        var model = new EditUserFormModel()
        {
            Id = user.Id,
            FirstName = user.FirstName,
            LastName = user.LastName,
            MiddleName = user.MiddleName,
            Login = user.Login,
            Number = user.Number,
            DateOfBirth = user.DateOfBirth.ToDateTime(TimeOnly.MinValue)
        };

        return View(model);
    }

    // POST: Users/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, EditUserFormModel model)
    {
        if (id != model.Id)
            return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                var user = await _context
                    .Users
                    .FirstOrDefaultAsync(u => u.Id == model.Id && u.Login == model.Login);

                if (user == null)
                    return NotFound();

                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.MiddleName = model.MiddleName;
                user.Number = model.Number;
                user.DateOfBirth = DateOnly.FromDateTime(model.DateOfBirth);

                if (!string.IsNullOrEmpty(model.Password))
                    user.Password = model.Password;

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(model.Id))
                    return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    // GET: Users/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return NotFound();

        var user = await _context.Users
            .FirstOrDefaultAsync(m => m.Id == id);

        if (user == null)
            return NotFound();

        var model = new DeleteUserFormModel()
        {
            Id = user.Id,
            FirstName = user.FirstName,
            LastName = user.LastName,
            MiddleName = user.MiddleName,
            Login = user.Login,
            Number = user.Number,
            DateOfBirth = user.DateOfBirth,
            AppRole = user.GetRole()
        };

        return View(model);
    }

    // POST: Users/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var user = await _context.Users.FindAsync(id);

        if (user != null)
            _context.Users.Remove(user);
        

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool UserExists(int id)
    {
        return _context.Users.Any(e => e.Id == id);
    }

    private void SetAppRoles(int? id = null)
    {
        var appRoles = new List<(string, int)>();
        appRoles.Add(new("Администратор", 1));
        appRoles.Add(new("Преподователь", 2));
        appRoles.Add(new("Родитель", 3));

        var roles = appRoles.Select(x => new { Id = x.Item2, Name = x.Item1 });

        ViewBag.AppRoles = id == null
            ? new SelectList(roles, "Id", "Name")
            : new SelectList(roles, "Id", "Name", id);
    }
}

Diplom/WebApplicationMVC/Views/Students/Create.cshtml
@model WebApplicationMVC.ViewModels.Students.CreateStudentFormModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>

    <div class="d-flex align-items-center mb-4">
        <div class="me-3" style="margin-left: -60px;">
            <a asp-controller="Students" asp-action="Index" class="text-decoration-none text-dark">
                <i class="bi bi-arrow-left fs-3"></i>
            </a>
        </div>

        <div class="container">
            <h4>Ученик</h4>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
                    @if (!ViewData.ModelState.IsValid)
                    {
                        foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                        {
                            <div class="text-danger">@error.ErrorMessage</div>
                        }
                    }
                    
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label">Фамилия</label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label">Имя</label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>                    <div class="form-group">
                        <label asp-for="MiddleName" class="control-label">Отчество</label>
                        <input asp-for="MiddleName" class="form-control" />
                        <span asp-validation-for="MiddleName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateOfBirth" class="control-label">Дата рождения</label>
                        <input asp-for="DateOfBirth" class="form-control" />
                        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check mb-3">
                        <input asp-for="IsPrivate" class="form-check-input" type="checkbox" id="isPrivateCheckbox" />
                        <label class="form-check-label" for="isPrivateCheckbox">Индивидуальное занятие</label>
                    </div>

                    <div class="form-group" id="groupSelect">
                        <label asp-for="GroupId" class="control-label">Группа</label>
                        <select asp-for="GroupId" class="form-control" asp-items="ViewBag.Groups">
                            <option value="">-- выберите группу --</option>
                        </select>
                    </div>

                    <div class="form-group" id="courseSelect">
                        <label asp-for="CourseId" class="control-label">Курс</label>
                        <select asp-for="CourseId" class="form-control" asp-items="ViewBag.Courses">
                            <option value="">-- выберите курс --</option>
                        </select>
                    </div>

                    <div class="form-group" id="teacherSelect">
                        <label asp-for="TeacherId" class="control-label">Преподаватель</label>
                        <select asp-for="TeacherId" class="form-control" asp-items="ViewBag.Teachers">
                            <option value="">-- выберите преподавателя --</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="ParentId" class="control-label">Родитель</label>
                            <select asp-for="ParentId" class="form-control" asp-items="ViewBag.Parents"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Balance">Баланс</label>
                        <input asp-for="Balance" class="form-control" />
                        <span asp-validation-for="Balance" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Создать" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        </div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }

        <script>
            function toggleFields() {
                const isPrivate = document.getElementById('isPrivateCheckbox').checked;
                const groupSelect = document.getElementById('groupSelect');
                const courseSelect = document.getElementById('courseSelect');
                const teacherSelect = document.getElementById('teacherSelect');

                if (isPrivate) {
                    groupSelect.style.display = 'none';
                    document.querySelector('[name="GroupId"]').value = "";
                    courseSelect.style.display = 'block';
                    teacherSelect.style.display = 'block';
                } else {
                    groupSelect.style.display = 'block';
                    courseSelect.style.display = 'none';
                    teacherSelect.style.display = 'none';
                    document.querySelector('[name="CourseId"]').value = "";
                    document.querySelector('[name="TeacherId"]').value = "";
                }
            }

            document.getElementById('isPrivateCheckbox').addEventListener('change', toggleFields);
            window.addEventListener('DOMContentLoaded', toggleFields);
        </script>
    }

</body>
</html>

Diplom/WebApplicationMVC/Views/Students/Delete.cshtml
@model WebApplicationMVC.ViewModels.Students.DeleteStudentViewModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>

    <div class="d-flex align-items-center mb-4">
        <div class="me-3" style="margin-left: -60px;">
            <a asp-controller="Students" asp-action="Index" class="text-decoration-none text-dark">
                <i class="bi bi-arrow-left fs-3"></i>
            </a>
        </div>

        <div class="container">
            <h3>Вы уверены что хотите удалить это?</h3>
        </div>
    </div>
    <h4>Ученик</h4>
    <div class="container">
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Фамилия
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                Имя
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                Отчеcтво
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MiddleName)
            </dd>

            <dt class="col-sm-2">
                Дата рождения
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DateOfBirth)
            </dd>
            <dt class="col-sm-2">
                Группа
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.GroupName)
            </dd>
            <dt class="col-sm-2">
                Родитель
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ParentName)
            </dd>
        </dl>
    
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Удалить" class="btn btn-danger" />
        </form>
</div>
</body>
</html>

Diplom/WebApplicationMVC/Views/Students/Details.cshtml
@model WebApplicationMVC.ViewModels.Students.StudentDetailsViewModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>

<div>
        <div class="d-flex align-items-center mb-4">
            <div class="me-3" style="margin-left: -60px;">
                <a asp-controller="Students" asp-action="Index" class="text-decoration-none text-dark">
                    <i class="bi bi-arrow-left fs-3"></i>
                </a>
            </div>

            <div class="container">
                <h4>Ученик</h4>
            </div>
        </div>
        <div class="container">
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Фамилия
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            Имя
        </dt>
        <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            Отчеcтво
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt class = "col-sm-2">
            Дата рождения
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
                Группа
        </dt>
        <dd class = "col-sm-10">
                <a asp-controller="Groups" asp-action="Details" 
                asp-route-id="@Model.GroupId">@Html.DisplayFor(model => model.GroupName)</a>
        </dd>
        <dt class = "col-sm-2">
            Родитель
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentName)
        </dd>
    </dl>
</div>
    <div class="button-container">
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-custom">Редактировать</a>
    </div>
    </div>
</body>
</html>

Diplom/WebApplicationMVC/Views/Students/Index.cshtml
@model IEnumerable<WebApplicationMVC.ViewModels.Students.StudentViewModel>

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/css/Index.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>

<body>
    <div class="main-container">
        <a asp-controller="Admin" asp-action="Index" class="btn back-button">
            <i class="bi bi-arrow-left fs-3"></i>
        </a>
        <div class="content-container">
            <div class="page-title">
                <h1>Ученики</h1>
            </div>
        <div class="action-bar">
            <div class="search-container">
                <input type="text" placeholder="Поиск" id="searchInput" />
            </div>
            <a asp-action="Create" class="btn btn-custom btn-add">Добавить</a>
        </div>
        <table class="table">
            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {
                    var item = Model.ElementAt(i);
                    <tr>
                        <td>@(i + 1)</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StudentName)
                        </td>
                        <td>
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-custom">Информация</a>

                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-custom">Редактировать</a>
                        </td>
                        <td>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-custom">Удалить</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        </div>
    </div>
    <script src="~/js/site.js"></script>

</body>
</html>