Diplom/WebApplicationMVC/ViewModels/Users/DeleteUserFormModel.cs
namespace WebApplicationMVC.ViewModels.Users;

public class DeleteUserFormModel
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string? MiddleName { get; set; }
    public string Login { get; set; }
    public string Number { get; set; }
    public DateOnly DateOfBirth { get; set; }
    public string AppRole { get; set; }
}

Diplom/WebApplicationMVC/ViewModels/Users/UserDetailsViewModel.cs
namespace WebApplicationMVC.ViewModels.Users;

public class UserDetailsViewModel
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string? MiddleName { get; set; }
    public string Login { get; set; }
    public string Number { get; set; }
    public DateOnly DateOfBirth { get; set; }
    public string AppRole { get; set; }
    public bool IsParent => AppRole == "Родитель";
    public bool IsTeacher => AppRole == "Преподователь";
}

Diplom/WebApplicationMVC/Controllers/AdminController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVC.Models.Database;

namespace WebApplicationMVC.Controllers;

[Authorize("admin")]
public class AdminController : Controller
{
    private readonly AppDbContext _context;

    public AdminController(AppDbContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        var avatarDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "avatars");
        var allAvatars = Directory.GetFiles(avatarDir).Select(Path.GetFileName).ToList();
        var rng = new Random();
        ViewBag.Avatar = allAvatars.Any()
            ? "/images/avatars/" + allAvatars[rng.Next(allAvatars.Count)]
            : "/images/icon.png";

        //для отображения в ЛК
        if (int.TryParse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value, out int userId))
        {
            var user = _context.Users.FirstOrDefault(u => u.Id == userId);
            if (user != null)
            {
                ViewBag.Phone = user.Number;
                ViewBag.Email = user.Login;
                ViewBag.FullName = $"{user.LastName} {user.FirstName} {user.MiddleName}";
            }
        }

        return View();
    }
}

Diplom/WebApplicationMVC/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVC.Models.Database;
using WebApplicationMVC.ViewModels.Groups;

namespace WebApplicationMVC.Controllers;

[Authorize("admin")]
public class GroupsController : Controller
{
    private readonly AppDbContext _context;

    public GroupsController(AppDbContext context)
    {
        _context = context;
    }

    // GET: Groups
    public async Task<IActionResult> Index()
    {
        var grps = await _context
            .Groups
            .Include(g => g.Students)
            .Include(g => g.Course)
            .Include(g => g.Teacher)
            .ToListAsync(); ;

        var groups = await _context
            .Groups
            .Include(g => g.Students)
            .Include(g => g.Course)
            .Include(g => g.Teacher)
            .Select(g => new GroupViewModel()
            {
                Id = g.Id,
                Name = g.Name,
                CourseName = g.Course.Name,
                TeacherName = g.Teacher.LastName + " " + g.Teacher.FirstName + (g.Teacher.MiddleName != null ? " " + g.Teacher.MiddleName : "")

            })
            .ToListAsync();

        return View(groups);
    }

    // GET: Groups/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();

        var group = await _context
            .Groups
            .Include(g => g.Students)
            .Include(g => g.Course)
            .Include(g => g.Teacher)
            .FirstOrDefaultAsync(g => g.Id == id);

        if (group == null)
            return NotFound();

        var gropViewModel = new GroupViewModel()
        {
            Id = group.Id,
            Name = group.Name,
            CourseName = group.Course.Name,
            TeacherName = group.Teacher.LastName + " " + group.Teacher.FirstName + (group.Teacher.MiddleName != null ? " " + group.Teacher.MiddleName : "")

        };

        return View(gropViewModel);
    }

    // GET: Groups/Create
    public async Task<IActionResult> Create()
    {
        await SetCoursesForViewBagAsync();
        await SetTeachersForViewBagAsync();
        return View();
    }

    // POST: Groups/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateGroupFormModel model)
    {
        if (ModelState.IsValid)
        {
            var teacher = await _context
                .Users
                .FirstOrDefaultAsync(x => x.Id == model.TeacherId && x.AppRole == AppRole.Teacher);

            if (teacher == null || teacher.AppRole != AppRole.Teacher)
            {
                ModelState.AddModelError("TeacherId", "Ошибка при выборе преподователя");
                await SetTeachersForViewBagAsync(model.TeacherId);
                await SetCoursesForViewBagAsync(model.CourseId);
                return View(model);
            }

            var course = await _context
                .Courses
                .FirstOrDefaultAsync(x => x.Id == model.CourseId);

            if (course == null)
            {
                ModelState.AddModelError("CourseId", "Ошибка при выборе курса");
                await SetTeachersForViewBagAsync(model.TeacherId);
                await SetCoursesForViewBagAsync(model.CourseId);
                return View(model);
            }

            var group = new Group()
            {
                Name = model.Name,
                Course = course,
                Teacher = teacher,
                GroupType = GroupType.Regular
            };

            _context.Add(group);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction(nameof(Create));
    }

    // GET: Groups/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
            return NotFound();

        var group = await _context
            .Groups
            .Include(g => g.Students)
            .FirstOrDefaultAsync(g => g.Id == id);

        if (group == null)
            return NotFound();

        var groupEditModel = new EditGroupFormModel()
        {
            Id = group.Id,
            Name = group.Name,
            CourseId = group.CourseId,
            TeacherId = group.TeacherId,
        };

        await SetCoursesForViewBagAsync(group.CourseId);
        await SetTeachersForViewBagAsync(group.TeacherId);
        return View(groupEditModel);
    }

    // POST: Groups/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, EditGroupFormModel model)
    {
        if (id != model.Id)
            return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                var group = await _context.Groups.FirstOrDefaultAsync(x => x.Id == model.Id);
                if (group == null)
                    return NotFound();

                var course = await _context
                   .Courses
                   .FirstOrDefaultAsync(x => x.Id == model.CourseId);

                if (course == null)
                    // Todo: по хорошему нужно дать нормально понять пользователю, что указанный user не может быть учителем
                    return NotFound();

                var teacher = await _context
                    .Users
                    .FirstOrDefaultAsync(x => x.Id == model.TeacherId && x.AppRole == AppRole.Teacher);

                if (teacher == null || teacher.AppRole != AppRole.Teacher)
                    // Todo: по хорошему нужно дать нормально понять пользователю, что указанный user не может быть учителем
                    return NotFound();

                group.Name = model.Name;
                group.CourseId = model.CourseId;
                group.TeacherId = model.TeacherId;

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await IsGroupExistAsync(model.Id))
                    return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }

        await SetCoursesForViewBagAsync(model.CourseId);
        await SetTeachersForViewBagAsync(model.TeacherId);
        return View(model);
    }

    // GET: Groups/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return NotFound();

        var group = await _context
            .Groups
            .Include(g => g.Students)
            .Include(g => g.Course)
            .FirstOrDefaultAsync(g => g.Id == id);

        if (group == null)
            return NotFound();

        var deleteGroupModel = new DeleteGroupFormModel()
        {
            Id = group.Id,
            Name = group.Name,
            CourseName = group.Course.Name,
        };

        return View(deleteGroupModel);
    }

    // POST: Groups/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var group = await _context.Groups.FindAsync(id);

        // Todo: нужна проверка, что у группы нет студентов.
        // Иначе нельзя удалить
        if (group != null)
        {
            _context.Groups.Remove(@group);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private async Task<bool> IsGroupExistAsync(int id)
    {
        return await _context.Groups.AnyAsync(e => e.Id == id);
    }

    private async Task SetCoursesForViewBagAsync(int? id = null)
    {
        var courses = await _context
            .Courses
            .Select(x => new { Id = x.Id, Name = x.Name })
            .ToListAsync();

        ViewBag.Courses = id == null 
            ? new SelectList(courses, "Id", "Name") 
            : new SelectList(courses, "Id", "Name", id);
    }

    private async Task SetTeachersForViewBagAsync(int? id = null)
    {
        var teachers = await _context
            .Users
            .Where(x => x.AppRole == AppRole.Teacher)
            .Select(x => new { Id = x.Id, Name = $"{x.LastName} {x.FirstName}{(x.MiddleName != null ? " " + x.MiddleName : "")}" })
            .ToListAsync();

        ViewBag.Teachers = id == null 
            ? new SelectList(teachers, "Id", "Name") 
            : new SelectList(teachers, "Id", "Name", id);
    }
    public async Task<IActionResult> ListByTeacher(int teacherId)
    {
        var teacherGroups = await _context
            .Groups
            .Include(u => u.Students)
            .Where(g => g.TeacherId == teacherId)  // предполагаем, что у тебя есть связь между группой и преподавателем
            .ToListAsync();

        if (teacherGroups == null || !teacherGroups.Any())
        {
            return NotFound();
        }

        return View(teacherGroups);  // Это отобразит представление ListByTeacher.cshtml
    }

}

Diplom/WebApplicationMVC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVC.Models.Database;
using WebApplicationMVC.ViewModels.Users;

namespace WebApplicationMVC.Controllers;

[Authorize("admin")]
public class UsersController : Controller
{
    private readonly AppDbContext _context;

    public UsersController(AppDbContext context)
    {
        _context = context;
    }

    // GET: Users
    public async Task<IActionResult> Index()
    {
        var users = await _context
            .Users
            .Select(u => new UserViewModel()
            {
                Id = u.Id,
                UserName = u.FirstName + " " + u.LastName + " " + u.MiddleName,
                AppRole = u.GetRole()
            })
            .ToListAsync();
        return View(users);
    }

    // GET: Users/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();

        var user = await _context.Users
            .Select(u => new UserDetailsViewModel()
            {
                Id = u.Id,
                FirstName = u.FirstName,
                LastName = u.LastName,
                MiddleName = u.MiddleName,
                Login = u.Login,
                Number = u.Number,
                DateOfBirth = u.DateOfBirth,
                AppRole = u.GetRole()
            })
            .FirstOrDefaultAsync(m => m.Id == id);
        if (user == null)
            return NotFound();

        return View(user);
    }

    // GET: Users/Create
    public IActionResult Create()
    {
        SetAppRoles();
        return View();
    }

    // POST: Users/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateUserFormModel model)
    {
        if (await _context.Users.AnyAsync(u => u.Login == model.Login))
        {
            ModelState.AddModelError("Login", "This login is already taken.");
            SetAppRoles(model.AppRole);
            return View(model);
        }

        if (ModelState.IsValid)
        {
            var user = new User()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                MiddleName = model.MiddleName,
                Login = model.Login,
                Number = model.Number,
                Password = model.Password,
                DateOfBirth = DateOnly.FromDateTime(model.DateOfBirth),
                AppRole = (AppRole)model.AppRole
            };
            _context.Add(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        SetAppRoles(model.AppRole);
        return View(model);
    }

    // GET: Users/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
            return NotFound();

        var user = await _context.Users.FindAsync(id);
        if (user == null)
            return NotFound();

        var model = new EditUserFormModel()
        {
            Id = user.Id,
            FirstName = user.FirstName,
            LastName = user.LastName,
            MiddleName = user.MiddleName,
            Login = user.Login,
            Number = user.Number,
            DateOfBirth = user.DateOfBirth.ToDateTime(TimeOnly.MinValue)
        };

        return View(model);
    }

    // POST: Users/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, EditUserFormModel model)
    {
        if (id != model.Id)
            return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                var user = await _context
                    .Users
                    .FirstOrDefaultAsync(u => u.Id == model.Id && u.Login == model.Login);

                if (user == null)
                    return NotFound();

                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.MiddleName = model.MiddleName;
                user.Number = model.Number;
                user.DateOfBirth = DateOnly.FromDateTime(model.DateOfBirth);

                if (!string.IsNullOrEmpty(model.Password))
                    user.Password = model.Password;

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(model.Id))
                    return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    // GET: Users/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return NotFound();

        var user = await _context.Users
            .FirstOrDefaultAsync(m => m.Id == id);

        if (user == null)
            return NotFound();

        var model = new DeleteUserFormModel()
        {
            Id = user.Id,
            FirstName = user.FirstName,
            LastName = user.LastName,
            MiddleName = user.MiddleName,
            Login = user.Login,
            Number = user.Number,
            DateOfBirth = user.DateOfBirth,
            AppRole = user.GetRole()
        };

        return View(model);
    }

    // POST: Users/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var user = await _context.Users.FindAsync(id);

        if (user != null)
            _context.Users.Remove(user);
        

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool UserExists(int id)
    {
        return _context.Users.Any(e => e.Id == id);
    }

    private void SetAppRoles(int? id = null)
    {
        var appRoles = new List<(string, int)>();
        appRoles.Add(new("Администратор", 1));
        appRoles.Add(new("Преподователь", 2));
        appRoles.Add(new("Родитель", 3));

        var roles = appRoles.Select(x => new { Id = x.Item2, Name = x.Item1 });

        ViewBag.AppRoles = id == null
            ? new SelectList(roles, "Id", "Name")
            : new SelectList(roles, "Id", "Name", id);
    }
}

Diplom/WebApplicationMVC/Views/Users/Create.cshtml
@model WebApplicationMVC.ViewModels.Users.CreateUserFormModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>

<div class="d-flex align-items-center mb-4">
    <div class="me-3" style="margin-left: -60px;">
        <a asp-controller="Users" asp-action="Index" class="text-decoration-none text-dark">
            <i class="bi bi-arrow-left fs-3"></i>
        </a>
    </div>

    <div class="container">
            <h4>Пользователь</h4>
    </div>
</div>
<div class="container">
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Фамилия</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">Имя</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label">Отчество</label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Login" class="control-label">E-mail</label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label">Пароль</label>
                <div class="input-group">
                    <input asp-for="Password" class="form-control" id="passwordInput" />
                    <button type="button" class="btn btn-outline-secondary" onclick="generatePassword()" title="Generate Password">
                        <i class="bi bi-shuffle"></i>
                    </button>
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
                <small id="copyMessage" class="form-text text-success" style="display:none;">Пароль скопирован!</small>

            <div class="form-group">
                <label asp-for="Number" class="control-label">Номер телефона</label>
                <input asp-for="Number" class="form-control" type="tel" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label">Дата рождения</label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="AppRole" class="control-label">Роль</label>
                <select asp-for="AppRole" class="form-control" asp-items="ViewBag.AppRoles"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-custom" />
            </div>
        </form>
    </div>
</div>

</div>


</body>
</html>

<script type="text/javascript">
    function generatePassword(length = 12) {
        const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!#$%^&*()";
        let password = "";
        for (let i = 0; i < length; i++) {
            const randomIndex = Math.floor(Math.random() * charset.length);
            password += charset[randomIndex];
        }
        document.getElementById("passwordInput").value = password;
        
        // copy password
        const input = document.getElementById("passwordInput");
        input.select();
        input.setSelectionRange(0, 99999);
        navigator.clipboard.writeText(input.value).then(function () {
            const msg = document.getElementById("copyMessage");
            msg.style.display = "block";
            setTimeout(() => msg.style.display = "none", 2000);
        });

        input.blur();
    }


</script>

Diplom/WebApplicationMVC/Views/Users/Delete.cshtml
@model WebApplicationMVC.ViewModels.Users.DeleteUserFormModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>

    <div class="d-flex align-items-center mb-4">
        <div class="me-3" style="margin-left: -60px;">
            <a asp-controller="Users" asp-action="Index" class="text-decoration-none text-dark">
                <i class="bi bi-arrow-left fs-3"></i>
            </a>
        </div>

        <div class="container">
            <h3>Вы уверены что хотите удалить это?</h3>
        </div>
    </div>
    <h4>Пользователь</h4>
    <div class="container">
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Фамилия
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                Имя
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                Отчеcтво
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MiddleName)
            </dd>
            <dt class = "col-sm-2">
                E-mail
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Login)
            </dd>
            <dt class = "col-sm-2">
                Номер телефона
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Number)
            </dd>
            <dt class = "col-sm-2">
                Дата рождения
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.DateOfBirth)
            </dd>
            <dt class="col-sm-2">
                Роль
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AppRole)
            </dd>
        </dl>
    
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Удалить" class="btn btn-danger" />
        </form>
</div>
</body>
</html>

Diplom/WebApplicationMVC/Views/Users/Details.cshtml
@model WebApplicationMVC.ViewModels.Users.UserDetailsViewModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>

<div>
        <div class="d-flex align-items-center mb-4">
            <div class="me-3" style="margin-left: -60px;">
                <a asp-controller="Users" asp-action="Index" class="text-decoration-none text-dark">
                    <i class="bi bi-arrow-left fs-3"></i>
                </a>
            </div>

            <div class="container">
                <h4>Пользователь</h4>
            </div>
        </div>
        <div class="container">
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Фамилия
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            Имя
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            Отчеcтво
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class = "col-sm-2">
            E-mail
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Login)
        </dd>
        <dt class = "col-sm-2">
            Номер телефона
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            Дата рождения
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            Роль
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppRole)
        </dd>
    </dl>
</div>
        <div class="button-container mt-3">
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-custom">Редактировать</a>

            @if (Model.IsParent)
            {
                <a asp-controller="Students" asp-action="ListByParent" asp-route-parentId="@Model.Id" class="btn btn-secondary ms-2">
                    Дети
                </a>
            }

            @if (Model.IsTeacher)
            {
                <a asp-controller="Groups" asp-action="ListByTeacher" asp-route-teacherId="@Model.Id" class="btn btn-secondary ms-2">
                    Группы
                </a>
            }
        </div>
    </div>
</body>
</html>

Diplom/WebApplicationMVC/Views/Users/Index.cshtml
@model IEnumerable<WebApplicationMVC.ViewModels.Users.UserViewModel>

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/css/Index.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>

<body>
    <div class="main-container">
        <a asp-controller="Admin" asp-action="Index" class="btn back-button">
            <i class="bi bi-arrow-left fs-3"></i>
        </a>

        <div class="content-container">
            <div class="page-title">
                <h1>Пользователи</h1>
            </div>
        <div class="action-bar">
            <div class="search-container">
                <input type="text" placeholder="Поиск" id="searchInput" />
            </div>
            <a asp-action="Create" class="btn btn-custom btn-add">Добавить</a>
        </div>
        <table class="table">
            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {
                    var item = Model.ElementAt(i);
                    <tr>
                        <td>@(i + 1)</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AppRole)
                        </td>
                        <td>
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-custom">Информация</a>

                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-custom">Редактировать</a>
                        </td>
                        <td>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-custom">Удалить</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        </div>
        </div>

    <script src="~/js/site.js"></script>

</body>
</html>