Diplom/WebApplicationMVC/ViewModels/Courses/CourseViewModel.cs
namespace WebApplicationMVC.ViewModels.Courses;

public class CourseViewModel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

Diplom/WebApplicationMVC/ViewModels/Courses/CreateCourseFormModel.cs
namespace WebApplicationMVC.ViewModels.Courses;

public class CreateCourseFormModel
{
    public string Name { get; set; }
    public string Description { get; set; }
    public int GroupPrice { get; set; }
    public int IndividualPrice { get; set; }
}

Diplom/WebApplicationMVC/ViewModels/Courses/DeleteCourseFormModel.cs
namespace WebApplicationMVC.ViewModels.Courses;

public class DeleteCourseFormModel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

Diplom/WebApplicationMVC/ViewModels/Courses/EditCourseFormModel.cs
namespace WebApplicationMVC.ViewModels.Courses;

public class EditCourseFormModel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int GroupPrice { get; set; }
    public int IndividualPrice { get; set; }
}

Diplom/WebApplicationMVC/Controllers/AdminController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVC.Models.Database;

namespace WebApplicationMVC.Controllers;

[Authorize("admin")]
public class AdminController : Controller
{
    private readonly AppDbContext _context;

    public AdminController(AppDbContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        var avatarDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "avatars");
        var allAvatars = Directory.GetFiles(avatarDir).Select(Path.GetFileName).ToList();
        var rng = new Random();
        ViewBag.Avatar = allAvatars.Any()
            ? "/images/avatars/" + allAvatars[rng.Next(allAvatars.Count)]
            : "/images/icon.png";

        //для отображения в ЛК
        if (int.TryParse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value, out int userId))
        {
            var user = _context.Users.FirstOrDefault(u => u.Id == userId);
            if (user != null)
            {
                ViewBag.Phone = user.Number;
                ViewBag.Email = user.Login;
                ViewBag.FullName = $"{user.LastName} {user.FirstName} {user.MiddleName}";
            }
        }

        return View();
    }
}

Diplom/WebApplicationMVC/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplicationMVC.Models.Database;
using WebApplicationMVC.ViewModels.Courses;

namespace WebApplicationMVC.Controllers;

[Authorize("admin")]
public class CoursesController : Controller
{
    private readonly AppDbContext _context;

    public CoursesController(AppDbContext context)
    {
        _context = context;
    }

    // GET: Courses
    public async Task<IActionResult> Index()
    {
        ViewData["Breadcrumb"] = new List<(string Text, string? Url)>
        {
            ("Курсы", null)
        };

        var courses = await _context.Courses.ToListAsync();

        var courseViewModels = courses
            .Select(c => new CourseViewModel
            {
                Id = c.Id,
                Name = c.Name,
                Description = c.Description
            })
            .ToList();
        return View(courseViewModels);
    }

    // GET: Courses/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var course = await _context.Courses
            .FirstOrDefaultAsync(m => m.Id == id);
        if (course == null)
        {
            return NotFound();
        }

        var courseViewModel = new CourseViewModel()
        {
            Id = course.Id,
            Name = course.Name,
            Description = course.Description
        };

        return View(courseViewModel);
    }

    // GET: Courses/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Courses/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateCourseFormModel model)
    {
        if (ModelState.IsValid)
        {
            var course = new Course()
            {
                Name = model.Name,
                Description = model.Description,
                GroupPrice = model.GroupPrice,
                IndividualPrice = model.IndividualPrice
            };

            _context.Add(course);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        
        return View(model);
    }

    // GET: Courses/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var course = await _context.Courses.FindAsync(id);
        if (course == null)
            return NotFound();

        var editCourseFormModel = new EditCourseFormModel()
        {
            Id = course.Id,
            Name = course.Name,
            Description = course.Description,
            GroupPrice = course.GroupPrice,
            IndividualPrice = course.IndividualPrice
        };
        
        return View(editCourseFormModel);
    }

    // POST: Courses/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, EditCourseFormModel model)
    {
        if (id != model.Id)
            return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                var course = await _context.Courses.FirstOrDefaultAsync(c => c.Id == model.Id);

                if (course == null)
                    return NotFound();

                course.Name = model.Name;
                course.Description = model.Description;
                course.GroupPrice = model.GroupPrice;
                course.IndividualPrice = model.IndividualPrice;

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await IsCourseExistAsync(model.Id))
                    return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    // GET: Courses/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return NotFound();

        var course = await _context.Courses
            .FirstOrDefaultAsync(m => m.Id == id);

        if (course == null)
            return NotFound();

        var deleteCourseModel = new DeleteCourseFormModel()
        {
            Id = course.Id,
            Name = course.Name,
            Description = course.Description,
        };

        return View(deleteCourseModel);
    }

    // POST: Courses/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var course = await _context.Courses.FindAsync(id);

        if (course != null)
        {
            // Todo: необходимо проверять есть ли у кура группы. Если есть, то запретить удаление
            _context.Courses.Remove(course);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private async Task<bool> IsCourseExistAsync(int id)
    {
        return await _context.Courses.AnyAsync(e => e.Id == id);
    }
}

Diplom/WebApplicationMVC/Views/Courses/Create.cshtml
@model WebApplicationMVC.ViewModels.Courses.CreateCourseFormModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>

<body>
    <div class="d-flex align-items-center mb-4">
        <div class="me-3" style="margin-left: -60px;">
            <a asp-controller="Courses" asp-action="Index" class="text-decoration-none text-dark">
                <i class="bi bi-arrow-left fs-3"></i>
            </a>
        </div>

        <div class="container">
            <h4>Курс</h4>
        </div>
    </div>
 <div class="container">
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Название</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">Описание</label>
                    <textarea asp-for="Description" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GroupPrice" class="control-label">Цена группового занятий</label>
                    <input asp-for="GroupPrice" class="form-control" />
                    <span asp-validation-for="GroupPrice" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="IndividualPrice" class="control-label">Цена индивидуального занятия</label>
                    <input asp-for="IndividualPrice" class="form-control" />
                    <span asp-validation-for="IndividualPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                        <input type="submit" value="Создать" class="btn btn-custom" />
                </div>
            </form>
        </div>
    </div>

</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Diplom/WebApplicationMVC/Views/Courses/Delete.cshtml
@model WebApplicationMVC.ViewModels.Courses.DeleteCourseFormModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>

    <div class="d-flex align-items-center mb-4">
        <div class="me-3" style="margin-left: -60px;">
            <a asp-controller="Courses" asp-action="Index" class="text-decoration-none text-dark">
                <i class="bi bi-arrow-left fs-3"></i>
            </a>
        </div>

        <div class="container">
            <h3>Вы уверены что хотите удалить это?</h3>
        </div>
    </div>
    <h4>Курс</h4>
    <div class="container">
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                Название
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-2">
                Описание
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
    
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Удалить" class="btn btn-danger" />
        </form>
</div>
</body>
</html>

Diplom/WebApplicationMVC/Views/Courses/Details.cshtml
@model WebApplicationMVC.ViewModels.Courses.CourseViewModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>

    <div class="d-flex align-items-center mb-4">
        <div class="me-3" style="margin-left: -60px;">
            <a asp-controller="Courses" asp-action="Index" class="text-decoration-none text-dark">
                <i class="bi bi-arrow-left fs-3"></i>
            </a>
        </div>

        <div class="container">
            <h4>Курс</h4>
        </div>
    </div>
    <div class="container">
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Название
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Описание
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>

<div class="button-container">
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-custom">Редактировать</a>
</div>
</body>
</html>

Diplom/WebApplicationMVC/Views/Courses/Edit.cshtml
@model WebApplicationMVC.ViewModels.Courses.EditCourseFormModel

@{
    // Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <link rel="stylesheet" href="~/css/action.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>

    <div class="d-flex align-items-center mb-4">
        <div class="me-3" style="margin-left: -60px;">
            <a asp-controller="Courses" asp-action="Index" class="text-decoration-none text-dark">
                <i class="bi bi-arrow-left fs-3"></i>
            </a>
        </div>

        <div class="container">
            <h4>Курс</h4>
        </div>
    </div>
    <div class="container">
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label">Название</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label">Описание</label>
                        <textarea asp-for="Description" class="form-control" rows="5"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="GroupPrice" class="control-label">Цена группового занятия</label>
                        <input asp-for="GroupPrice" class="form-control" />
                        <span asp-validation-for="GroupPrice" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="IndividualPrice" class="control-label">Цена индивидуального занятия</label>
                        <input asp-for="IndividualPrice" class="form-control" />
                        <span asp-validation-for="IndividualPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                            <input type="submit" value="Сохранить" class="btn btn-save" />
                    </div>
                </form>
            </div>
        
    </div>
 
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Diplom/WebApplicationMVC/Views/Courses/Index.cshtml
@model IEnumerable<WebApplicationMVC.ViewModels.Courses.CourseViewModel>

@{
    // Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/css/Index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

</head>

<body>
    <!-- Контейнер для кнопки "Вернуться назад" с отступами слева от контента -->
    <div class="main-container">
        <a asp-controller="Admin" asp-action="Index" class="btn back-button">
            <i class="bi bi-arrow-left fs-3"></i>
        </a>

        <div class="content-container">
            <div class="page-title">
                <h1>Курсы</h1>
            </div>

            <div class="action-bar">
                <div class="search-container">
                    <input type="text" placeholder="Поиск" id="searchInput" />
                    <i class="bi bi-search search-icon"></i>
                </div>
                <a asp-action="Create" class="btn btn-custom btn-add">Добавить</a>
            </div>

            <table class="table">
                <tbody>
                    @for (int i = 0; i < Model.Count(); i++)
                    {
                        var item = Model.ElementAt(i);
                        <tr>
                            <td>@(i + 1)</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-custom">Информация</a>
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-custom">Редактировать</a>
                            </td>
                            <td>
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-custom">Удалить</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <script src="~/js/site.js"></script>

</body>
</html>